- hosts: all
  
  tasks: 
    - name: Deploy environment
      become: yes
      lineinfile: 
        path: /etc/environment
        line: 'http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"'
        state: present
   
    - name: Install python3
      become: yes
      apt: 
       name: ['python3']
       update_cache: yes
       state: latest

    - name: Install git
      become: yes
      apt: 
        name: ['git']
        update_cache: yes
        state: latest

    - name: Install apache2
      become: yes
      apt: 
       name: ['apache2']
       update_cache: yes
       state: latest

    - name: Install couchdb
      become: yes
      git: 
        repo: "https://git-wip-us.apache.org/repos/asf/couchdb.git"
        dest: "{{ couchdb_install_dir }}"
        accept_hostkey: yes
        version: "{{ couchdb_version }}"

    - name: install couchdb
      become: yes
      apt:
        name: ['couchdb']
        update_cache: yes
        state: latest  
  

