---
- name: Create volume1 snapshot
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name_1 }}'
    display_name: "{{ item.vol_name_1 }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'  
#  loop: '{{ volumes }}'

- name: Create volume2 snapshot
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name_2 }}'
    display_name: "{{ item.vol_name_2 }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'  